services:
  - type: web
    name: facebook-browser-lite
    runtime: python
    plan: free  # Using free tier for lightweight deployment
    buildCommand: |
      pip install -r requirements.txt
      # Install minimal Chrome dependencies
      apt-get update && apt-get install -y \
        wget \
        gnupg \
        unzip \
        --no-install-recommends && \
      # Install Chrome
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
      echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list && \
      apt-get update && \
      apt-get install -y google-chrome-stable --no-install-recommends && \
      # Install ChromeDriver manually
      CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1) && \
      echo "Chrome version: $CHROME_VERSION" && \
      wget -q "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}" -O /tmp/chromedriver_version && \
      CHROMEDRIVER_VERSION=$(cat /tmp/chromedriver_version) && \
      echo "Installing ChromeDriver version: $CHROMEDRIVER_VERSION" && \
      wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O /tmp/chromedriver.zip && \
      unzip -q /tmp/chromedriver.zip -d /usr/bin/ && \
      chmod +x /usr/bin/chromedriver && \
      # Cleanup
      apt-get clean && \
      rm -rf /var/lib/apt/lists/* /tmp/*
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WDM_LOCAL
        value: "1"
      - key: CHROME_BIN
        value: "/usr/bin/google-chrome-stable"
      - key: CHROMEDRIVER_PATH
        value: "/usr/local/bin/chromedriver"
    healthCheckPath: /health
    autoDeploy: true
