services:
  - type: web
    name: facebook-browser-lite
    runtime: python
    plan: free  # Using free tier for lightweight deployment
    buildCommand: |
      pip install -r requirements.txt
      # Install Chrome browser and dependencies for headless operation
      apt-get update && apt-get install -y \
        wget \
        gnupg \
        unzip \
        curl \
        xvfb \
        libxi6 \
        libgconf-2-4 \
        libxss1 \
        libappindicator1 \
        libindicator7 \
        libasound2 \
        libpangocairo-1.0-0 \
        libatk1.0-0 \
        libcairo-gobject2 \
        libgtk-3-0 \
        libnspr4 \
        libxcomposite1 \
        libxcursor1 \
        libxdamage1 \
        libxtst6 \
        fonts-liberation \
        libnss3 \
        libgbm1 \
        --no-install-recommends && \
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
      echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list && \
      apt-get update && \
      apt-get install -y google-chrome-stable --no-install-recommends && \
      apt-get clean && \
      rm -rf /var/lib/apt/lists/*
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WDM_LOCAL
        value: "1"
      - key: CHROME_BIN
        value: "/usr/bin/google-chrome-stable"
      - key: CHROMEDRIVER_PATH
        value: "/usr/local/bin/chromedriver"
    healthCheckPath: /health
    autoDeploy: true
